### ISSUE TITLE
Robust Peak Detection - Autofocus 

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#157]
We should implement a method that fits the autofocus data with a Gaussian, as well as some other metrics, to make sure that we aren’t just finding the max value in a noisy signal.

**Comment by AdvancedImagingUTSW** [comment]
Kinda an interestingly annoying curve fitting problem. Would probably be best handled with a discontinuous fitting approach...

<img width="983" alt="image" src="https://user-images.githubusercontent.com/42547789/233069361-ec721a25-006d-4262-a526-03fc54022b26.png">

Tried several things, and sadly the spline fit is best.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/42547789/233069623-e4071b66-20a7-4a7a-b36f-69d8b0c402e2.png">

**Comment by zacsimile** [comment]
Hmm, I think it should be fit by the power tent function just fine. How are `x` and `y` generated?

Does changing `start_vals` to `[30, 0.002, 0.002, 1, 0.1]` work any better?
