### ISSUE TITLE
Photometrics Camera Support

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#279]
Reto seems interested in using our software with a photometric Kinetix camera.  Fortunately, I think mesoSPIM has done some of the work for us, and has some code available already [here](https://github.com/mesoSPIM/mesoSPIM-control/blob/3ef2033b0d029e5f3e421c715f52f23d0dd29ed4/mesoSPIM/src/mesoSPIM_Camera.py#L431)

@DaetwylerStephan - Don't you also have these cameras working with your software too?

For troubleshooting purposes, I just happen to have an unused Iris15B in our lab.

**Comment by AdvancedImagingUTSW** [comment]
Now that we are getting closer with @JinlongL's microscope, it is time to get the Photometrics camera implemented. This should not impact other parts of the code which most of our microscopes are heavily reliant on, so hopefully is minimally disruptive to multiscale, CT-ASLMv1, v2...

**Comment by zacsimile** [comment]
We should ask @DaetwylerStephan for his code. He did most of this already.

**Comment by AdvancedImagingUTSW** [comment]
https://github.com/Photometrics/PyVCAM

Photometrics Iris 15 - I believe it is operating on a Windows 10 machine. @mehr0096 or @JinlongL, can you confirm this?

The camera Drivers, etc., have already been installed and are functioning on the machine. And yes, we should also ask Stephan how far he made it. @DaetwylerStephan - did you make much progress?

**Comment by JinlongL** [comment]
IRIS 15 on Windows 10 Pro

**Comment by DaetwylerStephan** [comment]
Yes, I think I implemented quite a few/most of the functions - but I also noted that you made progress on the camera class. I'm happy to help getting the Photometrics to work soon! When I tried to run it, I had some issues with writing to the buffer.

**Comment by AdvancedImagingUTSW** [comment]
Hey @DaetwylerStephan, I appreciate it.  If you have implemented most of it, then I assume @annie-xd-wang will be able to get it to the finish line without that much pain. Could you push whatever code you have to this branch? 

`279-photometrics-camera-support`
