### ISSUE TITLE
self.is_acquiring as DCAM API parameter

### ISSUE THREAD

**Issue by DaetwylerStephan** [TheDeanLab/ASLM#286]
I would suggest to remove self.is_acquiring out of the API class and move it to the camera base class as not every API has a self.is_acquiring function. Or is there a reason why self.is_acquiring is inside the Hamamatsu API? (Is a very easy fix)

**Comment by AdvancedImagingUTSW** [comment]
Switching to a priority task so that we can move forward with the Photometrics camera support next.

**Comment by zacsimile** [comment]
This isn't a limiting factor for Photometrics support.
