### ISSUE TITLE
Merge AO Features

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#302]
We would like to merge @conorhughmcfadden recent AO features into the software.  Presumably, the best way to move forward is for Conor to commit his current functioning code as a new branch, then make a new branch from this and merge develop into this branch, and make sure that all unit tests and functionality remains.  Once that is established, we can then make a pull request.  At that time, we will need:

- Minimal documentation for the hardware (how to install, etc).  Should edit the hardware documentation source file for this...
- Some unit tests for the adaptive optics routine in our testing directory.

**Comment by zacsimile** [comment]
Superseded by #309.
