### ISSUE TITLE
Pause during confocal projection mode

### ISSUE THREAD

**Issue by BingyingChen** [TheDeanLab/ASLM#434]
```
Waveform with 1.0 planes is of length (22500,)
c:\users\multiscale\git\aslm\src\aslm\controller\sub_controllers\waveform_tab_controller.py:288: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  self.view.fig.tight_layout()
C:\Users\MultiScale\.conda\envs\ASLM\lib\tkinter\__init__.py:814: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  func(*args)
C:\Users\MultiScale\.conda\envs\ASLM\lib\site-packages\nidaqmx\errors.py:140: DaqWarning:
Warning 200010 occurred.

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
  warnings.warn(DaqWarning(
C:\Users\MultiScale\.conda\envs\ASLM\lib\site-packages\nidaqmx\errors.py:140: DaqWarning:
Warning 200010 occurred.

Finite acquisition or generation has been stopped before the requested number of samples were acquired or generated.
  warnings.warn(DaqWarning(
```

![image](https://user-images.githubusercontent.com/64285901/234380654-69e3f318-9513-4908-9d4c-ae9214ad1e46.png)

In the developed branch, there's a pause during the acquisition under confocal projection mode. The settings and error message shows above. 

[model_debug.log](https://github.com/TheDeanLab/ASLM/files/11326019/model_debug.log)
[view_controller_debug.log](https://github.com/TheDeanLab/ASLM/files/11326021/view_controller_debug.log)

**Comment by zacsimile** [comment]
One thing to note is here is `c:\users\multiscale\git\aslm\src\aslm\controller\sub_controllers\waveform_tab_controller.py:288: UserWarning: Creating legend with loc="best" can be slow with large amounts of data.
  self.view.fig.tight_layout()` runs even when the camera tab is selected. This indicates that the waveform controller plotting is getting executed even when the plot is not visible. This is a new thing, and is rather expensive for confocal projection mode. We should switch it back to only plotting when the waveform tab is accessed. Unclear if this is the source of the pause or a separate issue.

**Comment by BingyingChen** [comment]
Annie found out this is due to the length difference between the wavefront and the camera. The error in the green channel has been fixed. But it remains in the rest channels and probably causes another issue. 

![error-0503](https://user-images.githubusercontent.com/64285901/236062196-2125525b-1676-48a5-8c26-ed82cf88be6b.PNG)

It didn't show up after restarting the software. Perhaps a one-time thing. Will update it here if it shows up again.
