### ISSUE TITLE
Duplicated half-images after setting ROI size to 2048x1024

### ISSUE THREAD

**Issue by BingyingChen** [TheDeanLab/ASLM#435]
![image](https://user-images.githubusercontent.com/64285901/234383495-ad72a68d-8a7c-4267-96df-eb5c059566cc.png)

Saved image is the correct size, but the image is duplicated.

![image](https://user-images.githubusercontent.com/64285901/234383982-ed7d7992-4b62-480b-95f2-d0ce717b2e8d.png)

[model_debug.log](https://github.com/TheDeanLab/ASLM/files/11326135/model_debug.log)
[view_controller_debug.log](https://github.com/TheDeanLab/ASLM/files/11326136/view_controller_debug.log)

**Comment by annie-xd-wang** [comment]
The reason is that we reversed the height and width of ROI.
