### ISSUE TITLE
Multiposition table focus needs to be ignored when switching from low to high res

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#436]
Need to implement an option where, if we create a multiposition table with a high-res target, we ignore the focus positions in the multiposition table when we switch to high res. In general, microscopes with decoupled focusing stages need to ignore focusing information passed in between them. Probably needs to be a flag.

**Comment by AdvancedImagingUTSW** [comment]
Hi @annie-xd-wang, we just had a meeting with Zach, Jinlong, Torikul (collaborator in Sean's lab). This appears to be a bottleneck that might not take too much effort (hopefully). Any chance you can meet with @zacsimile and quickly come up with a plan?
