### ISSUE TITLE
Associate metadata with MIPs

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#438]
We'd like to store the full dataset's metadata in the header of its MIP. I propose moving the MIP saving to the data source classes to most easily accomplish this. Any objections, @AdvancedImagingUTSW? @annie-xd-wang?

**Comment by AdvancedImagingUTSW** [comment]
Seems very reasonable as a form of redundancy

**Comment by zacsimile** [comment]
I'm particularly interested in doing this for the OMERO import.

**Comment by AdvancedImagingUTSW** [comment]
Would be nice to know what git hash data was collected with too.

[for example...](https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script)

**Comment by zacsimile** [comment]
We presently stash the ASLM software version in the metadata. We could make it more specific with a hash. Let's make a different issue for this, since it's not MIP-specific.

**Comment by zacsimile** [comment]
Presently inclined to not add metadata to MIPs, as it may not be necessary. Worked with BioHPC yesterday and we discovered that the data transfer rates for symlinks to full data sets was sufficiently low to be teneble. New plan is to create a symlink (`ln -s`) to full data sets stored in `/archive/shared/MIL` and then `omero import` the symlink. The full data set includes metadata. Command is (roughly, sans user/passwords) `omero import --skip checksum -x $(readlink file_to_import.tiff) --transfer=ln_s file_to_import.tiff`.

**Comment by zacsimile** [comment]
No longer necessary.
