### ISSUE TITLE
Large number of entries in a multiacquisition table slows down initial imaging

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#450]
After running `VolumeSearch`, if I have a large number of entries in the multi-acquisition table, it takes a long time to start an acquisition. I press `Acquire` and it takes about 30 seconds to start. If I delete the positions, it is quick again.

**Comment by AdvancedImagingUTSW** [comment]
We naively jammed the pandas table into there since it worked with tk, and Annie kindly made it functional. But it may honestly be one of our weakest dependencies. We could easily consider something else.

**Comment by zacsimile** [comment]
Further investigation reveals the slowdown comes not from `pandas`, but from `aslm.config.config.build_nested_dict()`. Likely from multiple assignments to the `multiprocessing.Manager()` object, possibly slower due to recursion.

**Comment by AdvancedImagingUTSW** [comment]
Now that I am using the Volume Search feature, this is rearing its ugly head again...

**Comment by AdvancedImagingUTSW** [comment]
I have also seen something where the multi position table must have at least one entry in it, or else an error is thrown.
