### ISSUE TITLE
Add ability to toggle stage boundaries

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#456]
Add a GUI checkbox to toggle stage boundaries on or off. If unchecked, we can move the stage anywhere. When checked, the stage follows what is set in `x_min`, `x_max`, etc. in the `stage` section of `configuration.yaml`.

**Comment by AdvancedImagingUTSW** [comment]
How about a menu item?

**Comment by AdvancedImagingUTSW** [comment]
This PR is now addressed in #457. Waiting for review.

**Comment by AdvancedImagingUTSW** [comment]
<img width="501" alt="image" src="https://github.com/TheDeanLab/ASLM/assets/42547789/87a2edb4-5547-4ebe-add3-8ba991f9b321">
