### ISSUE TITLE
Camera display blinking after long acquisition

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#478]
https://github.com/TheDeanLab/ASLM/assets/1263313/bd3e1f3b-b9a9-4b09-907c-a3e8ba4fb733

There is intermittent blinking of the camera display, even with auto scale turned off. The camera frames appear and disappear.

**Comment by AdvancedImagingUTSW** [comment]
Is this still a problem? I don't think I have seen it for a bit.

**Comment by zacsimile** [comment]
Yes, still a problem. You have to image for a while continuously.
