### ISSUE TITLE
stage hot keys disabled when stage hits limits

### ISSUE THREAD

**Issue by mehr0096** [TheDeanLab/ASLM#501]
I noticed when testing hot keys that the stage movement hot keys are disabled once the stage hits limits. Disabling stage limits and using stop stage allows for stage to be moved again though.

**Comment by zacsimile** [comment]
These hot keys aren't disabled, we are just updating to a position that is still outside the stage bounds when using them. Once stop stage is hit or stage limits are disabled, this should work again.
