### ISSUE TITLE
Program froze on Stop continuous mode

### ISSUE THREAD

**Issue by JinlongL** [TheDeanLab/ASLM#511]
Not a common problem. Happened once. No errors thrown. Logs attached.
[view_controller_debug.log](https://github.com/TheDeanLab/ASLM/files/12053133/view_controller_debug.log)
[model_debug.log](https://github.com/TheDeanLab/ASLM/files/12053134/model_debug.log)

**Comment by zacsimile** [comment]
Closing as this has not repeated itself.
