### ISSUE TITLE
Storage stage limits enabled/disabled in `experiment.yml`

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#519]
Make it so if we close + reopen the program with disabled stage limits, they remain disabled.

**Comment by zacsimile** [comment]
Partially addressed in https://github.com/TheDeanLab/ASLM/commit/757b917c8734bdde135c5d9b06a3b33c49765114. Stage limits are presently disabled by default.

**Comment by annie-xd-wang** [comment]
The parameter has been added in #547

**Comment by AdvancedImagingUTSW** [comment]
@annie-xd-wang - If this parameter has been added in #547, and it is functioning properly, can you close out this issue?
