### ISSUE TITLE
Add flipx/flipy/flipz flags to `configuration.yaml` for stages

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#520]
Assume by default that increasing X, Y, or Z moves the sample closer to the objectives (further into the field of view). Use this information when saving positions of tiles during acquisition so that the tiled image comes out in the right order. Currently, this is done for `VolumeSearch` and can be changed on a per-scope basis using the plugin architecture for features. We should generalize this behavior.

**Comment by AdvancedImagingUTSW** [comment]
This will have some serious ramifications for features and microscope operation.

My interpretation is that when we do flipX = True, then essentially, when we normally tell the stage to move + 500 microns, it would move -500 microns. 

Alternatively, we could consider multiplying our absolute stage position by negative 1.  

What exactly did you have in mind @zacsimile ?

**Comment by zacsimile** [comment]
Your interpretation is correct. Right now I implement it with a sign flip in `VolumeSearch`, which is effectively the same as saying move `-500` instead of `+500`.
