### ISSUE TITLE
Z-stack tiling not as good as X and Y stacks

### ISSUE THREAD

**Issue by 3vwylie** [TheDeanLab/ASLM#545]
I was given this task by @zacsimile and @JinlongL.

**Comment by AdvancedImagingUTSW** [comment]
Get after it! Thanks for the help.

**Comment by AdvancedImagingUTSW** [comment]
@zacsimile, does this work well on your microscope? If so, it might be because the Z stage is different than the other stages. It is linearly encoded.

**Comment by zacsimile** [comment]
Addressed in #552.
