### ISSUE TITLE
Specify wait_number as an attribute of model

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#567]
Currently, wait number is called in 4 different locations in the model. It seems as if this is an opportunity for different values to be implemented.  Perhaps we set it as an attribute, so that we only have to change it once? I would probably also change the name to something more descriptive, such as `camera_wait_iterations`.

@annie-xd-wang - What do you think?

```        wait_num = 20  # this will let this thread wait 10 * 500 ms before it ends```

**Comment by annie-xd-wang** [comment]
I think you’re totally right. We should define a parameter once and use the parameter.
