### ISSUE TITLE
Tiling corners are transposed

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#597]
Top right/bottom left should be swapped. Not sure how this is happening.

![image](https://github.com/TheDeanLab/ASLM/assets/1263313/b6252600-6241-498e-b3e3-b89630ac8ec3)

**Comment by AdvancedImagingUTSW** [comment]
Not a stage or camera flip_x flip_y?

**Comment by zacsimile** [comment]
Not as far as I can tell. Also an issue on the dumb tiling. Feels like maybe the views are getting read into the BDV in the wrong order. Annie's working on this with me.
