### ISSUE TITLE
Turn off lasers whenever data thread is paused

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#604]
If the data thread is paused, the signal thread can continue moving stages but must turn off the laser until the data thread is resumed. This will prevent our samples from bleaching during long pauses.

**Comment by AdvancedImagingUTSW** [comment]
I feel like a better solution would be to toggle the lasers on immediately prior to an acquisition, and toggle them off immediately after, in all circumstances.

We turn the lasers on within the `microscope` object, `prepare_next_channel` method. To turn them off, we would just need to do the following...
```self.lasers[str(self.laser_wavelength[current_laser_index])].turn_off()```

**Comment by AdvancedImagingUTSW** [comment]
Made a quick push to linked branch that explicitly turns off the lasers after each image acquisition...

https://github.com/TheDeanLab/ASLM/tree/604-turn-off-lasers-whenever-data-thread-is-paused

**Comment by zacsimile** [comment]
Yeah this is a good idea. I think keeping the laser on in between acquisitions is what's causing this central stripe. If you look at the galvo waveforms, they are parking the beam in the center of the frame in between acquisitions. 

![image](https://github.com/TheDeanLab/ASLM/assets/1263313/9c59701b-6adc-49de-a1c2-89c325cf3b57)

![image](https://github.com/TheDeanLab/ASLM/assets/1263313/d95ba3f6-875d-454e-a7e1-750d11305952)

**Comment by zacsimile** [comment]
Can you PR this @AdvancedImagingUTSW  so we can test?

**Comment by AdvancedImagingUTSW** [comment]
That central stripe definitely appears to be a parked beam...  Hopefully this is sufficient to eliminate that.
