### ISSUE TITLE
ASI stage fails silently on incorrect `axes_mapping`

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#641]
If we do a lowercase `axes_mapping`, e.g. `[x, y, z]` instead of `[X, Y, Z]`, the ASI stage does not work properly, but fails to alert the user that they have provided non-existent axes in the axis mapping. We should check that the axes provided in `axes_mapping` exist within the available set of axes on the Tiger controller.

**Comment by AdvancedImagingUTSW** [comment]
I literally just ran into this error yesterday helping out the University of Colorado team that is building an OPM. 

Would be valuable to make sure that the ASI stages are capitalized, which should largely fix it (so long as that axis exists)

**Comment by jondaniels** [comment]
The ASI stage should respond identically to upper and lower case characters; the first thing the parser does is convert everything to uppercase.  If it does not I would appreciate knowing how to replicate the error.  Could the error be on the Python side?

If there is some error on the ASI side then a log of the serial traffic showing the problem would be very helpful.

**Comment by zacsimile** [comment]
@AdvancedImagingUTSW, yep, that fixes it.

@jondaniels No error on the ASI side. See #644.
