### ISSUE TITLE
Cleanup Requirements.txt and/or replace with pyproject.toml

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#657]
I'm pretty sure we no longer need tensor flow in the requirements, which would clean up the dependency install substantially. Could do this while updating to a pyproject.toml, if we think that is a good idea.

Also, the Capstone team will need this library: https://github.com/Mecademic/mecademicpy Not sure if we should add this to our requirements, add it as a sub-module, or install a static version in our API folder. Open for opinions.

**Comment by zacsimile** [comment]
I'm in favor of switching to `pyproject.toml` and having like a `robot` dependency set for the mecademic.

**Comment by AdvancedImagingUTSW** [comment]
Started some work on this on the linked branch. The pyproject.toml is defined and appears to work for the main application. Sphinx fails currently when I try `make html`

**Comment by AdvancedImagingUTSW** [comment]
@conorhughmcfadden could you list any dependencies you need for the AO in addition to what is standard?
