### ISSUE TITLE
Exposure time not updated properly. 

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [TheDeanLab/ASLM#728]
**Describe the bug**
Strange error, perhaps related to one that @JinlongL reported a while back with the filter wheel. It seems as if the software doesn't grab the most recent state of the channel settings. For example, we cranked up the exposure time for the far-red channel here, but when we started the exposure, the green channel also has this exposure. 

![image](https://github.com/TheDeanLab/navigate/assets/42547789/7e557d8b-2cb6-4ab5-afa4-77a1535558f6)

![image](https://github.com/TheDeanLab/navigate/assets/42547789/1a58b99e-1096-4c2e-97d7-2c7e4aa08281)

**Comment by zacsimile** [comment]
So the "Framerate Info" is updated independently of the rest of the software in `channels_tab_controller.execute()`. We can see on line 877 of `channels_tab_controller.py` that "Exposure time (ms)" is set to the maximum exposure time over all channels. I don't think this is propagated elsewhere, but it's worth checking.

**Comment by annie-xd-wang** [comment]
This bug is not caused by the controller side. It's because the sample counts passed to the DAQ are wrong. I'm fixing it.
