### ISSUE TITLE
ExASLM_Stage_Z_Stack_Issue

### ISSUE THREAD

**Issue by JinlongL** [TheDeanLab/ASLM#736]
When acquiring Z stack with ASI FTP2000 stage, some noticeable lines at the beginning and the middle of MIP of axial planes (xz, yz). 

This issue is fixed with backing the stage back to the starting position and move towards the start position 20 um. Probably some lead time is needed for the stage to get ready for each Z stack acquisition.
No backup:
![IMG_8928](https://github.com/TheDeanLab/navigate/assets/96149064/b3538936-cd71-4cd2-8da0-bffe3eadd1af)
With backup:
![IMG_8929](https://github.com/TheDeanLab/navigate/assets/96149064/e95984e9-bc60-40c2-9d19-824ab039d87c)

**Comment by zacsimile** [comment]
What is the path forward here? Do we want to add a `lead_distance` option for ASI stages that automatically backs it off its starting position by `lead_distance` whenever a ZStack (or other non-live acquisition) is started?

**Comment by JinlongL** [comment]
Hi Zach,

Thank you for checking on this. I think adding some lead time could be the best option here until they fix the bug.

Thanks,
Jinlong
________________________________

**Comment by AdvancedImagingUTSW** [comment]
Presumably fixed with hardware changes. Can reactivate if this resurfaces.
