### ISSUE TITLE
Modify saving approach during custom acquisition

### ISSUE THREAD

**Issue by zacsimile** [TheDeanLab/ASLM#764]
Ideally checking "Save Data" should work the same in "Customized" mode as in ZStackAcquisition. Currently we use a custom writer in Customized mode.

**Comment by AdvancedImagingUTSW** [comment]
@annie-xd-wang is going to propose a couple possibilities. At that time, we can discuss and decide how to best move forward.

**Comment by annie-xd-wang** [comment]
Do you mean that we turn off the global writer in "Customized" mode and let each feature save its images? For example, let ZStack feature save z-stack images.

**Comment by annie-xd-wang** [comment]
The current solution uses the global image writer to save images. Each feature can mark a flag to indicate whether to save the frame.
