### ISSUE TITLE
Tab of laser power control

### ISSUE THREAD

**Issue by bojuichang** [TheDeanLab/ASLM#833]
I always need to be careful whether I enter 10% or 100% of the laser power. Because the size of the tab to enter the laser power is simply just too small. 

Can you make it larger? 
Thanks.

![image](https://github.com/TheDeanLab/navigate/assets/20553885/f3818c21-7a62-427e-b33e-3c431018a4fb)

**Comment by bojuichang** [comment]
I feel I don't see the change. The tab is still small.
![20240227](https://github.com/TheDeanLab/navigate/assets/20553885/a408e6f2-e509-47bb-af7c-611e7d5c1f3c)

**Comment by AdvancedImagingUTSW** [comment]
If I comment out the width value, it is supposed to default to a value of ~20 according to ttk documentation. This appears to be true:

```
            #  Laser Power Spinbox
            self.laserpower_variables.append(tk.StringVar())
            self.laserpower_pulldowns.append(
                ValidatedSpinbox(
                    self.frame_columns[2],
                    from_=0,
                    to=100.0,
                    textvariable=self.laserpower_variables[num],
                    increment=5,
                    #width=5,
                    font=tk.font.Font(size=11),
                )
            )
```
![image](https://github.com/TheDeanLab/navigate/assets/42547789/d4fd7f1c-0c41-4504-b9f4-9692066b640e)

If I return the value to width to 5, I think it looks good.  It was previously set to 4, which might have been just a bit too tight.
![image](https://github.com/TheDeanLab/navigate/assets/42547789/50f4a86b-d71a-4312-9bcf-eb9ac88858d2)

**Comment by bojuichang** [comment]
Thanks for the effort. 
Is it possible to have something in between, like 4.2 or 4.5? I feel the width of 5 is a bit too large. ^^! The width of 4 seems to be a bit tight but personally, I think it is better. Or, maybe you can have the width of 4 and make the font smaller, like the one in the Laser or Filter settings. Nevertheless, both work for me. 
Again, thanks a lot.

**Comment by AdvancedImagingUTSW** [comment]
The value must be an integer, and changing the font size can be tricky since it can disrupt the spacing and alignment of the rows and columns. that's why the Laser and Filter settings have different font sizes; it aligns to the other variables in that section. I went ahead and merged it.
