### ISSUE TITLE
Stage controller initiates a move before the user finishes typing

### ISSUE THREAD

**Issue by SJShep** [TheDeanLab/ASLM#882]
This issue concerns the GUI stage control window. When typing a position in any of the X, Y, Z stage text entry boxes, the stage begins to move to the entered value before the user finishes typing and changes focus by leaving the text box. For example, if I pause for a moment at 10 while typing 1000, the stage starts moving to 10.

While I don't anticipate this being a frequent occurrence, it does introduce the risk of a collision. Could the text box be configured to update the stage only when the user leaves the text box?

**Comment by AdvancedImagingUTSW** [comment]
Ideally should be a focus out event only, or perhaps when the user presses `enter` or `tab`.

![image](https://github.com/TheDeanLab/navigate/assets/42547789/d6e08aa7-614d-44fc-bc29-837ef57260ca)
