### ISSUE TITLE
Light sheet mode synchronization issue with Photometrics Iris 15

### ISSUE THREAD

**Issue by SJShep** [TheDeanLab/ASLM#899]
Cannot optimize remote focus parameters when using the Photometrics Iris 15 in light sheet mode. There are a few problems, which seem related to synchronization:
1. Stopping and restarting acquire changes what we see with respect to the remote focusing.
    -  ![image](https://github.com/TheDeanLab/navigate/assets/67834563/eca38ccd-8cb5-409e-b892-3fc1ec98b422)
    -  Stop and start acquire: ![image](https://github.com/TheDeanLab/navigate/assets/67834563/4b0638eb-bc66-4f81-946f-8e74d85a9dc1)
2. After setting the parameters where the ASLM almost looks to be working, changing the exposure causes the current remote focus parameters to fail.
    -  ![image](https://github.com/TheDeanLab/navigate/assets/67834563/12b0d2ff-c154-47bb-a2f9-5ab6f38c484e)
    - ![image](https://github.com/TheDeanLab/navigate/assets/67834563/3b6eafd8-de83-469f-bff8-a2f231c2c126)

**Camera Configuration**
![image](https://github.com/TheDeanLab/navigate/assets/67834563/be85c451-8e3b-479a-b990-c520dc9a094e)

**Comment by annie-xd-wang** [comment]
Hi @SJShep, I've made a fix that should solve problem 1. Please test it with the branch [#899](https://github.com/TheDeanLab/navigate/tree/899-light-sheet-mode-synchronization-issue-with-photometrics-iris-15). 

For the waveform parameters, you could try reducing the camera delay time to a shorter value, such as 1 ms. This parameter is set in the configuration.yaml file. At the same time, set an appropriate flyback value and settle-down time for the remote focus through the GUI.

**Comment by SJShep** [comment]
That fixed the problem with stopping and starting the acquisitions.
![image](https://github.com/TheDeanLab/navigate/assets/67834563/86912ff5-246c-4ae1-a46e-0450fed8166c)
